# Generated by Django 4.2.19 on 2026-02-20 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Virtaul_App", "0002_studentprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAssessmentAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interests_snapshot", models.JSONField(blank=True, default=list)),
                ("skills_snapshot", models.JSONField(blank=True, default=list)),
                ("questions", models.JSONField(default=list)),
                ("answers", models.JSONField(blank=True, default=dict)),
                ("score", models.IntegerField(default=0)),
                ("total", models.IntegerField(default=10)),
                (
                    "model_name",
                    models.CharField(default="gemini-2.5-flash", max_length=80),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
