# Generated by Django 4.2.19 on 2026-02-20 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Virtaul_App", "0004_studentassessmentattempt_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentCareerReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report", models.JSONField(default=dict)),
                (
                    "model_name",
                    models.CharField(default="gemini-2.5-flash", max_length=80),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_report_obj",
                        to="Virtaul_App.studentassessmentattempt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
