# Generated by Django 4.2.19 on 2026-02-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Virtaul_App", "0005_studentcareerreport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentassessmentattempt",
            name="subject",
        ),
        migrations.AddField(
            model_name="studentassessmentattempt",
            name="career_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentassessmentattempt",
            name="career_model_name",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="studentassessmentattempt",
            name="career_recommendations",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
