# Generated by Django 4.2.19 on 2026-02-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Virtaul_App", "0006_remove_studentassessmentattempt_subject_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentassessmentattempt",
            name="subject",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
